### ISSUE TITLE
Pressing & releasing Ctrl switches frames

### ISSUE THREAD

**Issue by stefan-reich** [topalavlad/ComponentSwitcher#6]
Hi, this one's an actual bug... if you press Ctrl and just release it again, the switcher switches frames. Quite annoying...

I might hunt for the bug myself.

Edit: Haha, maybe it's not even your bug... might be mine :)

**Comment by topalavlad** [comment]
@stefan-reich - I suspect it's mine. Any chance you had the time to take a look at it?

**Comment by stefan-reich** [comment]
The bug is real... It can only be in dispatchKeyEvent, right? I'm adding debug messages.

**Comment by stefan-reich** [comment]
I think I fixed it. In hideMenu(), after `switchDialog.dispose();` add: `switchDialog = null;`

Without this, it tries to hide an already-hidden dialog. Also it's a memory leak

**Comment by stefan-reich** [comment]
OK maybe I got it... in hideMenu(), add: `switchDialog.unselect();` before `selected.setSelected(true);`

Then in SwitchDialog, add:

`public void unselect() {
    list.setSelectedIndex(-1);
}`

**Comment by stefan-reich** [comment]
Oops, OK, it doesn't work yet.

**Comment by stefan-reich** [comment]
Next try - in hideMenu(): `if (switchDialog != null && switchDialog.isVisible())` instead of the shorter condition

**Comment by stefan-reich** [comment]
Well! That last change seems to work.

**Comment by stefan-reich** [comment]
I believe it's fixed (see PR).
