### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by rahulpateel** [topalavlad/ComponentSwitcher#7]
Not working in my project

**Comment by rahulpateel** [comment]
Pls give me steps how to use it

**Comment by topalavlad** [comment]
Hi @rahulpateel. Are you using `JInternalFrames` in your application?

**Comment by rahulpateel** [comment]
Yes

**Comment by topalavlad** [comment]
@rahulpateel Can you post an example of how you used the library and tell me what exactly `Not working` means?

**Comment by topalavlad** [comment]
Please reopen if this is really an issue

**Comment by stefan-reich** [comment]
Worst bug description ever :D
